# Generated by Django 4.2.5 on 2023-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="status",
        ),
    ]
