# Generated by Django 4.2.5 on 2023-09-14 09:45

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_remove_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoncontent",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lesson_content/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "avi",
                            "mkv",
                            "pdf",
                            "mp3",
                        ]
                    )
                ],
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncontent",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Text"
            ),
        ),
    ]
