# Generated by Django 4.2.5 on 2023-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="jshshir",
            field=models.IntegerField(blank=True, null=True, verbose_name="Jshshir"),
        ),
    ]
