# Generated by Django 4.2.5 on 2023-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_jshshir"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
