# Generated by Django 4.2.5 on 2023-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Full name"
            ),
        ),
    ]
