# Generated by Django 4.2.5 on 2023-09-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vebinar", "0002_chatroom_rename_text_chat_content_chat_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="vebinar.chatroom",
            ),
            preserve_default=False,
        ),
    ]
