# Generated by Django 4.2.5 on 2023-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporaryuser",
            name="ball",
        ),
        migrations.AddField(
            model_name="temporaryuser",
            name="point",
            field=models.PositiveIntegerField(default=0, verbose_name="Point"),
        ),
    ]
