# Generated by Django 4.2.5 on 2023-09-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="test/files/")),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "image"), ("video", "video")], max_length=255
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="test",
            name="users",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="images",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="is_text_required",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="text_length",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="variants",
        ),
        migrations.RemoveField(
            model_name="testquestion",
            name="videos",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
        migrations.AddField(
            model_name="test",
            name="questions",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="test",
            name="resumbit_attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="user_test",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.usertest",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variant",
            name="is_true",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="variant",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variant",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.testquestion",
                verbose_name="Savolni tanlang",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="question",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("choice_order", "Choice Order"),
                    ("multi_select", "Multi-Select"),
                    ("single_select", "Single-Select"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="is_true",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.AddField(
            model_name="media",
            name="test_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.testquestion",
                verbose_name="Savolni tanlang",
            ),
        ),
    ]
