# Generated by Django 4.2.5 on 2023-09-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_test",
            "0002_media_remove_test_users_remove_testquestion_answer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=800, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="is_required",
            field=models.BooleanField(default=True, verbose_name="Majburiymi "),
        ),
        migrations.AddField(
            model_name="test",
            name="point",
            field=models.BigIntegerField(default=0, verbose_name="Berilgan Ball"),
        ),
        migrations.AddField(
            model_name="test",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.subject",
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.subject",
            ),
        ),
    ]
