# Generated by Django 4.2.5 on 2023-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_test",
            "0003_subject_test_is_required_test_point_test_subject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.subject",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.subject",
            ),
            preserve_default=False,
        ),
    ]
