# Generated by Django 4.2.5 on 2023-09-16 12:07

import apps.student_test.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0004_alter_test_subject_alter_testquestion_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="questions",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="time",
            field=models.DurationField(
                validators=[apps.student_test.validators.validate_min_duration]
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_test.test",
            ),
        ),
    ]
