# Generated by Django 4.2.5 on 2023-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0005_alter_test_questions_alter_test_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
