# Generated by Django 4.2.5 on 2023-09-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0006_alter_variant_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testquestion",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_to_test",
                to="student_test.test",
            ),
        ),
    ]
