# Generated by Django 4.2.5 on 2023-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0012_alter_variant_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
