# Generated by Django 4.2.5 on 2023-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0015_remove_usertest_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertest",
            name="start_time",
            field=models.DateTimeField(default="2023-09-17 23:30:00"),
            preserve_default=False,
        ),
    ]
