# Generated by Django 4.2.5 on 2023-09-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0016_usertest_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants_to_question",
                to="student_test.testquestion",
                verbose_name="Savolni tanlang",
            ),
        ),
    ]
