# Generated by Django 4.2.5 on 2023-09-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0017_alter_variant_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertest",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_test_to_test",
                to="student_test.test",
            ),
        ),
    ]
