# Generated by Django 4.2.5 on 2023-09-19 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student_test", "0019_vaqtinchalikuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VaqtinchalikUser",
            new_name="TemporaryUser",
        ),
    ]
