# Generated by Django 4.2.5 on 2023-09-19 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0020_rename_vaqtinchalikuser_temporaryuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemporaryUser",
        ),
    ]
