# Generated by Django 4.2.5 on 2023-09-19 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0021_delete_temporaryuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="resumbit_attempt_count",
            new_name="resubmit_attempt_count",
        ),
    ]
