# Generated by Django 4.2.5 on 2023-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0023_alter_variant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
