# Generated by Django 4.2.5 on 2023-09-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_test", "0024_alter_variant_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="user_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answer_to_user_test",
                to="student_test.usertest",
            ),
        ),
    ]
