# Generated by Django 4.2.5 on 2023-09-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_userchoice_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchoice",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_choice",
                to="main.pollchoice",
                verbose_name="Choice",
            ),
        ),
    ]
